// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class OmplaintTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void omplaint() {
    driver.get("https://www.youtube.com/watch?v=_ylSLyRJGh4");
    driver.manage().window().setSize(new Dimension(945, 1008));
    driver.findElement(By.cssSelector(".ytd-watch-metadata > #button-shape .yt-spec-touch-feedback-shape__fill")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ytd-watch-metadata > #button-shape .yt-spec-touch-feedback-shape__fill"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ytd-menu-popup-renderer:nth-child(3) .style-scope:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(1) > #radioLabel .text > .style-scope:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#input-2 > .style-scope")).click();
    driver.findElement(By.cssSelector(".style-scope:nth-child(2) > #menuButton > #dropdown > #contentWrapper .style-scope:nth-child(6)")).click();
    driver.findElement(By.cssSelector("#submit-button .yt-spec-touch-feedback-shape__fill")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector("#submit-button .yt-spec-touch-feedback-shape__fill")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#submit-button > .style-scope .yt-core-attributed-string"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#confirm-button .yt-spec-touch-feedback-shape__fill")).click();
  }
}
