// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchVideoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchVideo() {
    driver.get("https://www.youtube.com/playlist?list=PLlXQGa4zzXd5A4JuvIa-pmwiFIbuUwU1Z/");
    driver.manage().window().setSize(new Dimension(1050, 652));
    driver.findElement(By.name("search_query")).click();
    driver.findElement(By.name("search_query")).sendKeys("как сдать третью лабу по тпо");
    driver.findElement(By.name("search_query")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.cssSelector(".ytd-item-section-renderer:nth-child(1) > #dismissible .yt-core-image--fill-parent-height"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,345.3333435058594)");
    driver.findElement(By.cssSelector("#search-clear-button .yt-spec-touch-feedback-shape__fill")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".gsst_a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("thumbnail-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("search_query")).sendKeys("тпо клименков");
    driver.findElement(By.name("search_query")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.cssSelector(".ytd-item-section-renderer:nth-child(3) > #dismissible .yt-core-image--fill-parent-height"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(2) > .style-scope > #thumbnail > #overlays > .style-scope:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,137.3333282470703)");
    js.executeScript("window.scrollTo(0,86)");
    {
      WebElement element = driver.findElement(By.cssSelector(".style-scope:nth-child(2) > #content > .yt-simple-endpoint #video-title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
